### ISSUE TITLE
Access maybe?

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#1094]
Error reported in course COSC1306-17524 on page /runestone/assignments/chooseAssignment.html by user JonathanCastillo chazxavi88@gmail.com
I dont have a bug, but for some reason my screen is stuck on this mage when i try to access assignments maybe i accidentially clicked it
    ---------------- Traceback --------------
    Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/assignments.py", line 1188, in <module>
  File "/home/bmiller/Runestone/web2py/gluon/globals.py", line 421, in <lambda>
    self._caller = lambda f: f()
  File "/home/bmiller/Runestone/web2py/gluon/tools.py", line 3869, in f
    return action(*a, **b)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/assignments.py", line 756, in chooseAssignment
    ).select(orderby=db.assignments.duedate)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/objects.py", line 2395, in select
    return adapter.select(self.query, fields, attributes)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 763, in select
    return self._select_aux(sql, fields, attributes, colnames)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 719, in _select_aux
    rows = self._select_aux_execute(sql)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 713, in _select_aux_execute
    self.execute(sql)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/__init__.py", line 67, in wrap
    return f(*args, **kwargs)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 413, in execute
    rv = self.cursor.execute(command, *args[1:], **kwargs)
psycopg2.errors.UndefinedColumn: column assignments.nopause does not exist
LINE 1: ...ments"."from_source", "assignments"."nofeedback", "assignmen...
                                                             ^

**Comment by bnmnetp** [comment]
temporary glitch.  No need for sarcasm.
