### ISSUE TITLE
Changing order of items in assignment doesn't save

### ISSUE THREAD

**Issue by barbarer** [RunestoneInteractive/RunestoneComponents#1128]
I have created an assignment and move the items to change the order and then save but when I leave that assignment and come back the order isn't saved.  See py4e-int and assignment Midterm-1-Fall20-v2 for an example. I try to put them in the question order by the last value.

**Comment by barbarer** [comment]
I drag the left edge of the question and drop it when it is in the place I
want it and it moves correctly.  It just doesn't save it.

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by bnmnetp** [comment]
I got 20+ crash messages like this, all from you this morning:

```

Traceback (most recent call last):  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 219, in restricted    exec(ccode, environment)  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/admin.py", line 2773, in <module>  File "/home/bmiller/Runestone/web2py/gluon/globals.py", line 421, in <lambda>    self._caller = lambda f: f()  File "/home/bmiller/Runestone/web2py/gluon/tools.py", line 3862, in f    flag = condition()  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/admin.py", line 2219, in <lambda>    lambda: verifyInstructorStatus(auth.user.course_name, auth.user),  File "/home/bmiller/Runestone/web2py/applications/runestone/models/db.py", line 228, in verifyInstructorStatus    .select(db.courses.id, **SELECT_CACHE)  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/objects.py", line 2395, in select    return adapter.select(self.query, fields, attributes)  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 763, in select    return self._select_aux(sql, fields, attributes, colnames)  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 719, in _select_aux    rows = self._select_aux_execute(sql)  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 713, in _select_aux_execute    self.execute(sql)  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/__init__.py", line 67, in wrap    return f(*args, **kwargs)  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 413, in execute    rv = self.cursor.execute(command, *args[1:], **kwargs)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block
```

Unfortunately this is nearly useless, and I cannot cause the error to happen no matter how hard I try.  It appears to be crashing in the call to verifyInstructorStatus which happens thousands and thousands of times a day.  So I added a popup to warn you that the move did not save, AND I tried to make one simplification that may or may not have any change.  Those changes will launch on Saturday.

If you went and tried it now, it may very well work fine.

**Comment by barbarer** [comment]
Okay, I will test it on Saturday.

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by barbarer** [comment]
It seems to be working now.
