### ISSUE TITLE
Possible course start date problem

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#239]
Error reported in course DSFieldston on page /runestone/admin/startdate by user kvega kdragon87@gmail.com
I tried to change the start date of my course. Now can't access the change start date or rebuild functions.

---------------- Traceback --------------
Traceback (most recent call last):
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/restricted.py", line 212, in restricted
    exec ccode in environment
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/controllers/admin.py", line 1334, in <module>
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/globals.py", line 194, in <lambda>
    self._caller = lambda f: f()
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/tools.py", line 3022, in f
    return action(*a, **b)
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/controllers/admin.py", line 291, in startdate
    current_start_date = course.term_start_date.strftime("%m/%d/%Y")
ValueError: year=16 is before 1900; the datetime strftime() methods require year >= 1900

**Comment by bnmnetp** [comment]
Date was in the database as 0016 instead of 2016.  Fixed the database, and the new date picker should alleviate data entry problems.
