### ISSUE TITLE
Accessing a course STUDENT

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#291]
Error reported in course FoundProgr2016 on page /runestone/assignments/index?sid=67635 by user MaxG max.garagnani@gmail.com
Please describe what you were doing that led up to this error:

I logged in as instructor to this course; I went to the "Progress Page", and looked for "Michael Ghebru", because I wanted to give him access to the course as a Teaching Assistant. 
When I found the name, I clicked on it.
This generated the error.

---------------- Traceback --------------
Traceback (most recent call last):
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/restricted.py", line 212, in restricted
    exec ccode in environment
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/controllers/assignments.py", line 1000, in <module>
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/globals.py", line 194, in <lambda>
    self._caller = lambda f: f()
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/controllers/assignments.py", line 50, in index
    types_to_use == 'all'
UnboundLocalError: local variable 'types_to_use' referenced before assignment

**Comment by bnmnetp** [comment]
fixed
