### ISSUE TITLE
exercise details links to bug page

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#455]
Error reported in course CollegiateCS on page /runestone/dashboard/exercisemetrics?id=question1_8_2 by user MichaelMc michael.mccarrin@gmail.com
Please describe what you were doing that led up to this error:
Tried to click on Exercise details.

---------------- Traceback --------------
Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/dashboard.py", line 275, in <module>
  File "/home/bmiller/Runestone/web2py/gluon/globals.py", line 409, in <lambda>
    self._caller = lambda f: f()
  File "/home/bmiller/Runestone/web2py/gluon/tools.py", line 3964, in f
    return action(*a, **b)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/dashboard.py", line 248, in exercisemetrics
    data_analyzer.load_exercise_metrics(request.get_vars["id"])
  File "/home/bmiller/Runestone/web2py/applications/runestone/models/db_dashboard.py", line 364, in load_exercise_metrics
    self.problem_metrics = CourseProblemMetrics(self.course_id, self.users,self.db_chapter)
AttributeError: 'DashboardDataAnalyzer' object has no attribute 'db_chapter'

**Comment by bnmnetp** [comment]
fixed.
