### ISSUE TITLE
Can't access assignments

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#514]
Error reported in course CollegiateCS on page /runestone/assignments/doAssignment?assignment_id=270 by user MichaelMc michael.mccarrin@gmail.com
Please describe what you were doing that led up to this error: I was creating some activecode exercises. The last one I created included a datafile. After I created it, I found I was unable to access most of my assignments. Attempting access produces a crash that brings me to this page.

---------------- Traceback --------------
Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/assignments.py", line 1337, in <module>
  File "/home/bmiller/Runestone/web2py/gluon/globals.py", line 409, in <lambda>
    self._caller = lambda f: f()
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/assignments.py", line 1248, in doAssignment
    logger.debug("user_id = %s labels[chapters] = %s labels[sub_chapters] = %s",auth.user.id,labels['chapters'].chapter_label,labels['sub_chapters'].sub_chapter_label)
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by bnmnetp** [comment]
should be ok now.  I'm not exactly sure what happened to cause this to break.  Which makes me even more nervous!
