### ISSUE TITLE
Accessing Student info

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#534]
Error reported in course SB_Intro_CS_Python on page /runestone/dashboard/studentreport?id=G%C3%83%C2%A4g%C3%84%C2%99%C3%B0%C2%9F%C2%99%C2%8C by user MrsJakubielski amjakubielski@saint-bernard.com
Please describe what you were doing that led up to this error:
I am trying to access a specific student's info: Gage Goodwin and every time I click on his name I get directed to report a bug.  I seem to be able to access all the other students info except his.

---------------- Traceback --------------
Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/dashboard.py", line 286, in <module>
  File "/home/bmiller/Runestone/web2py/gluon/globals.py", line 409, in <lambda>
    self._caller = lambda f: f()
  File "/home/bmiller/Runestone/web2py/gluon/tools.py", line 3964, in f
    return action(*a, **b)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/dashboard.py", line 150, in studentreport
    data_analyzer.load_user_metrics(request.vars.id)
  File "/home/bmiller/Runestone/web2py/applications/runestone/models/db_dashboard.py", line 368, in load_user_metrics
    self.db_chapter_progress = db((db.user_sub_chapter_progress.user_id == self.user.id)).select(db.user_sub_chapter_progress.chapter_id,db.user_sub_chapter_progress.sub_chapter_id,db.user_sub_chapter_progress.status)
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by bnmnetp** [comment]
Yes, young gage seems to have created a very creative username:  Gägę🙌

This is not supported, but I suppose we should try to detect that at registration time.

**Comment by bnmnetp** [comment]
Write a javascript validation function to ensure that a username has only ascii characters in it before submitting a registration request.
