### ISSUE TITLE
Not able to view content

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#679]
Error reported in course py101 on page /runestone/assignments/practice by user ramnikbansal ramnik.bansal@gmail.com
Please describe what you were doing that led up to this error:

---------------- Traceback --------------
Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/assignments.py", line 622, in <module>
  File "/home/bmiller/Runestone/web2py/gluon/globals.py", line 409, in <lambda>
    self._caller = lambda f: f()
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/assignments.py", line 441, in practice
    now = datetime.datetime.utcnow() - datetime.timedelta(hours=int(session.timezoneoffset))
ValueError: invalid literal for int() with base 10: '-5.5'

**Comment by bnmnetp** [comment]
Fixed -- turns out to be easy as timedelta can take hours as a float :smile:
