### ISSUE TITLE
Removing Multiple Students

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#680]
Error reported in course cs925 on page /runestone/admin/removeStudents by user dvermes dvermes@scarsdaleschools.org
Please describe what you were doing that led up to this error:

I was trying to remove my students from last year and it gave me a Gateway Error.
---------------- Traceback --------------
Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/admin.py", line 1518, in <module>
  File "/home/bmiller/Runestone/web2py/gluon/globals.py", line 409, in <lambda>
    self._caller = lambda f: f()
  File "/home/bmiller/Runestone/web2py/gluon/tools.py", line 3964, in f
    return action(*a, **b)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/admin.py", line 563, in removeStudents
    for studentID in studentList:
TypeError: 'NoneType' object is not iterable

**Comment by bnmnetp** [comment]
Removing an entire class of students is not really a use case we are prepared for.  I'm sure that it timed out.  It would be much better to simply make a new class.
