### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#722]
Error reported in course LHSIntroCS_2018 on page /runestone/default/user/login?_next=/runestone/default/index by user lhs_5170345 achen345@student.fuhsd.org
Please describe what you were doing that led up to this error:
Tried to log in; entire process was very slow and resulted in this

---------------- Traceback --------------
Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/bmiller/Runestone/web2py/applications/runestone/models/db.py", line 23, in <module>
    migrate=False, migrate_enabled=(os.environ.get("WEB2PY_MIGRATE", "Yes") in ['Yes', 'Fake']))
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/base.py", line 170, in __call__
    obj = super(MetaDAL, cls).__call__(*args, **kwargs)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/base.py", line 475, in __init__
    "Failure to connect, tried %d times:\n%s" % (attempts, tb)
RuntimeError: Failure to connect, tried 5 times:
Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/base.py", line 455, in __init__
    self._adapter = adapter(**kwargs)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/postgres.py", line 25, in __call__
    return AdapterMeta.__call__(cls, *args, **kwargs)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/__init__.py", line 40, in __call__
    obj = super(AdapterMeta, cls).__call__(*args, **kwargs)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/postgres.py", line 48, in __init__
    driver_args, adapter_args, do_connect, after_connection)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 367, in __init__
    super(SQLAdapter, self).__init__(*args, **kwargs)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 52, in __init__
    self.reconnect()
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/helpers/classes.py", line 181, in _reconnect_and_configure
    self._connection_reconnect()
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/connection.py", line 152, in reconnect
    self.connection = self.connector()
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/postgres.py", line 105, in connector
    return self.driver.connect(**self.driver_args)
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections

**Comment by bnmnetp** [comment]
This is definitely an indication that the site is getting overwhelmed with requests.  I'll keep an eye on this.
