### ISSUE TITLE
Unable to reach 9.5

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#843]
Error reported in course thinkcspy on page /runestone/books/published/thinkcspy/Strings/StringMethods.html by user MrBeef23 bradenryates@gmail.com
Please describe what you were doing that led up to this error:
I was going through the course materials and just finished section 9.4. When I clicked on the link to 9.5, I was brought to the "Report a Bug" page.
---------------- Traceback --------------
Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/main.py", line 444, in wsgibase
    serve_controller(request, response, session)
  File "/home/bmiller/Runestone/web2py/gluon/main.py", line 183, in serve_controller
    page = run_view_in(response._view_environment)
  File "/home/bmiller/Runestone/web2py/gluon/compileapp.py", line 733, in run_view_in
    ccode = compile2(scode, filename)
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 205, in compile2
    return compile(code, layer, 'exec')
  File "/home/bmiller/Runestone/web2py/applications/runestone/books/thinkcspy/published/thinkcspy/Strings/StringMethods.html", line 33
    </span></code> and <code class="docutils literal notranslate"><span class="pre">
    ^
SyntaxError: invalid syntax

**Comment by bnmnetp** [comment]
The example of using double { was messing up the template engine.  Fixed
