### ISSUE TITLE
links on individual problems are not working on the student progress page.

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#844]
Error reported in course csapd2019 on page /runestone/dashboard/exercisemetrics?id=qListRem3&chapter=ListBasics by user johnqfig jfigliulo@css.edu
When I go to the student progress page and try to click on the links I get a 404 or this page depending on the type of link that I click on.
---------------- Traceback --------------
Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/dashboard.py", line 382, in <module>
  File "/home/bmiller/Runestone/web2py/gluon/globals.py", line 421, in <lambda>
    self._caller = lambda f: f()
  File "/home/bmiller/Runestone/web2py/gluon/tools.py", line 3869, in f
    return action(*a, **b)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/dashboard.py", line 299, in exercisemetrics
    data_analyzer.load_exercise_metrics(request.get_vars["id"])
  File "/home/bmiller/Runestone/web2py/applications/runestone/modules/db_dashboard.py", line 404, in load_exercise_metrics
    self.problem_metrics.update_metrics(self.course.course_name)
  File "/home/bmiller/Runestone/web2py/applications/runestone/modules/db_dashboard.py", line 127, in update_metrics
    (current.db.questions.chapter == self.chapter.chapter_label)
AttributeError: 'NoneType' object has no attribute 'chapter_label'

**Comment by bnmnetp** [comment]
I fixed the 404 problem. 

The Traceback is related to the fact that the csapd2019 course has been changing as it progresses and chapters that existed at one time (and are still stored in the database) are no longer there.  The Chapter referenced in the url is ListBasics, but ListBasics no longer exists.

This should not be an issue going forward.

Tagging @bhoffman0  FYI
