### ISSUE TITLE
links on individual problems are not working on the student progress page.

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#859]
Error reported in course csapd2019 on page /runestone/dashboard/index by user johnqfig jfigliulo@css.edu
Please describe what you were doing that led up to this error:

I had selected the role of instructor and tried to go to student progress.

---------------- Traceback --------------
Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/dashboard.py", line 448, in <module>
  File "/home/bmiller/Runestone/web2py/gluon/globals.py", line 421, in <lambda>
    self._caller = lambda f: f()
  File "/home/bmiller/Runestone/web2py/gluon/tools.py", line 3869, in f
    return action(*a, **b)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/dashboard.py", line 117, in index
    "chapter_title": chapget.ChapterName(chtmp),
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/dashboard.py", line 55, in ChapterName
    return self.Cmap[label].chapter_name
KeyError: 'GettingStarted'

**Comment by bnmnetp** [comment]
Fixed
