### ISSUE TITLE
Student Progress page crash

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#860]
Error reported in course csapd2019 on page /runestone/dashboard/index by user hoffmanb hoffmanb@elms.edu
I clicked on Student Progress in the Instructor's dashboard.

---------------- Traceback --------------
Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/dashboard.py", line 448, in <module>
  File "/home/bmiller/Runestone/web2py/gluon/globals.py", line 421, in <lambda>
    self._caller = lambda f: f()
  File "/home/bmiller/Runestone/web2py/gluon/tools.py", line 3869, in f
    return action(*a, **b)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/dashboard.py", line 118, in index
    "chapter_number": chapget.ChapterNumber(chtmp),
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/dashboard.py", line 50, in ChapterNumber
    return self.Cmap[label].chapter_num
KeyError: 'GettingStarted'

**Comment by bnmnetp** [comment]
Fixed
