### ISSUE TITLE
cant get in

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#936]
Error reported in course hscs on page / by user psuci peterasuciu@gmail.com
    Please describe what you were doing that led up to this error:

    ---------------- Traceback --------------
    Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/default.py", line 647, in <module>
  File "/home/bmiller/Runestone/web2py/gluon/globals.py", line 421, in <lambda>
    self._caller = lambda f: f()
  File "/home/bmiller/Runestone/web2py/gluon/tools.py", line 3869, in f
    return action(*a, **b)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/default.py", line 252, in index
    db.user_courses.insert(user_id=auth.user.id, course_id=auth.user.course_id)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/objects.py", line 762, in insert
    ret = self._db._adapter.insert(self, row.op_values())
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 487, in insert
    raise e
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 482, in insert
    self.execute(query)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/__init__.py", line 67, in wrap
    return f(*args, **kwargs)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 413, in execute
    rv = self.cursor.execute(command, *args[1:], **kwargs)
psycopg2.errors.ForeignKeyViolation: insert or update on table "user_courses" violates foreign key constraint "user_courses_user_id_fkey"
DETAIL:  Key (user_id)=(56117) is not present in table "auth_user".

**Comment by bnmnetp** [comment]
You may need to clear you cache in your browser as this was one of the users that was deleted manually today.  But if your session cookie is still active its going to try to take you to your course.

**Comment by bnmnetp** [comment]
Your students should be able to register for either of the courses you have created.
