### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#954]
Error reported in course CS4131Fall2019 on page /runestone/books/published/webfundamentals/Flask/templates.html by user gao00066@umn.edu gao00066@umn.edu
    Please describe what you were doing that led up to this error:

    ---------------- Traceback --------------
    Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/main.py", line 444, in wsgibase
    serve_controller(request, response, session)
  File "/home/bmiller/Runestone/web2py/gluon/main.py", line 183, in serve_controller
    page = run_view_in(response._view_environment)
  File "/home/bmiller/Runestone/web2py/gluon/compileapp.py", line 733, in run_view_in
    ccode = compile2(scode, filename)
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 205, in compile2
    return compile(code, layer, 'exec')
  File "/home/bmiller/Runestone/web2py/applications/runestone/books/webfundamentals/published/webfundamentals/Flask/templates.html", line 56
    </span> <span class="nv">name</span> <span class="cp">
    ^
SyntaxError: invalid syntax

**Comment by bnmnetp** [comment]
Just fixed it.
