### ISSUE TITLE
LP breaks under Sphinx 2.4.0

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#984]
```
# Sphinx version: 2.4.0
# Python version: 3.7.5 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.10.3
# Last messages:
#   Running Sphinx v2.4.0
#   building [mo]: all of 0 po files
#   building [html]: all source files
#   updating environment:
#   [new config]
#   2 added, 0 changed, 0 removed
#   reading sources... [ 50%] index
#   reading sources... [100%] lp_tester.s
# Loaded extensions:
#   sphinx.ext.mathjax (2.4.0) from /Users/bmiller/.virtualenvs/componentsdev/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /Users/bmiller/.virtualenvs/componentsdev/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /Users/bmiller/.virtualenvs/componentsdev/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /Users/bmiller/.virtualenvs/componentsdev/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /Users/bmiller/.virtualenvs/componentsdev/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /Users/bmiller/.virtualenvs/componentsdev/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /Users/bmiller/.virtualenvs/componentsdev/lib/python3.7/site-packages/alabaster/__init__.py
#   runestone.common (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/common/__init__.py
#   runestone.matrixeq (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/matrixeq/__init__.py
#   runestone.clickableArea (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/clickableArea/__init__.py
#   runestone.tabbedStuff (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/tabbedStuff/__init__.py
#   runestone.fitb (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/fitb/__init__.py
#   runestone.video (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/video/__init__.py
#   runestone.webgldemo (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/webgldemo/__init__.py
#   runestone.spreadsheet (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/spreadsheet/__init__.py
#   runestone.reveal (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/reveal/__init__.py
#   CodeChat.CodeToRestSphinx (1.7.2) from /Users/bmiller/.virtualenvs/componentsdev/lib/python3.7/site-packages/CodeChat/CodeToRestSphinx.py
#   runestone.lp (0.0.1) from /Users/bmiller/Runestone/RunestoneComponents/runestone/lp/__init__.py
#   runestone.parsons (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/parsons/__init__.py
#   runestone.meta (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/meta/__init__.py
#   runestone.animation (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/animation/__init__.py
#   runestone.assignment (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/assignment/__init__.py
#   runestone.server (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/server/__init__.py
#   runestone.question (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/question/__init__.py
#   runestone.assess (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/assess/__init__.py
#   runestone.shortanswer (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/shortanswer/__init__.py
#   runestone.chapterdb (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/chapterdb/__init__.py
#   runestone.pretext (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/pretext/__init__.py
#   runestone.codelens (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/codelens/__init__.py
#   runestone.activecode (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/activecode/__init__.py
#   runestone.datafile (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/datafile/__init__.py
#   runestone.usageAssignment (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/usageAssignment/__init__.py
#   runestone.external (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/external/__init__.py
#   runestone.showeval (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/showeval/__init__.py
#   runestone.blockly (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/blockly/__init__.py
#   runestone.accessibility (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/accessibility/__init__.py
#   runestone.dragndrop (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/dragndrop/__init__.py
#   runestone.disqus (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/disqus/__init__.py
#   runestone.poll (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/poll/__init__.py
#   runestone.utility (unknown version) from /Users/bmiller/Runestone/RunestoneComponents/runestone/utility/__init__.py
Traceback (most recent call last):
  File "/Users/bmiller/.virtualenvs/componentsdev/lib/python3.7/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/Users/bmiller/.virtualenvs/componentsdev/lib/python3.7/site-packages/sphinx/application.py", line 343, in build
    self.builder.build_all()
  File "/Users/bmiller/.virtualenvs/componentsdev/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 260, in build_all
    self.build(None, summary=__('all source files'), method='all')
  File "/Users/bmiller/.virtualenvs/componentsdev/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/Users/bmiller/.virtualenvs/componentsdev/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/Users/bmiller/.virtualenvs/componentsdev/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/Users/bmiller/.virtualenvs/componentsdev/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/Users/bmiller/.virtualenvs/componentsdev/lib/python3.7/site-packages/sphinx/io.py", line 284, in read_doc
    filetype = get_filetype(app.config.source_suffix, filename)
  File "/Users/bmiller/.virtualenvs/componentsdev/lib/python3.7/site-packages/sphinx/util/__init__.py", line 131, in get_filetype
    raise FiletypeNotFoundError
sphinx.errors.FiletypeNotFoundError
```

**Comment by bnmnetp** [comment]
My guess is that this must be related to the .s files ??

**Comment by bjones1** [comment]
Thanks for letting me know. I've released an updated version of CodeChat that should work. Would you check?

**Comment by bnmnetp** [comment]
That seems to have fixed it...  Thanks.

On a related note:  I am going to move our requirements*.txt files to requirements*.in and start using  pip-compile to create our requirements*.txt files.

This lets us keep the requirements.in file free of second level dependencies and allow us to manage just the packages we want.  pip-compile will create a fully frozen version of everything including dependencies.  The result will make our builds much more reproducible and eliminate these kinds of surprises.  We can be much more intentional now about upgrades to the packages we really rely on while letting pip-compile take care versioning the dependencies.

**Comment by bjones1** [comment]
Great! That's a great idea -- I need to take the same approach in another project I work on, where unexpected changes in secondary dependencies have caused difficult to find test failures.
