### ISSUE TITLE
8

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#990]
Error reported in course GHHS_CompSci_A on page /runestone/books/published/apcsareview/index.html by user DhruvJ dajoshi@students.wcpss.net
    Please describe what you were doing that led up to this error:

    ---------------- Traceback --------------
    Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/main.py", line 444, in wsgibase
    serve_controller(request, response, session)
  File "/home/bmiller/Runestone/web2py/gluon/main.py", line 179, in serve_controller
    page = run_controller_in(request.controller, request.function, environment)
  File "/home/bmiller/Runestone/web2py/gluon/compileapp.py", line 657, in run_controller_in
    ccode = getcfs(layer, filename, lambda: compile2(code, filename))
  File "/home/bmiller/Runestone/web2py/gluon/cfs.py", line 50, in getcfs
    data = filter()
  File "/home/bmiller/Runestone/web2py/gluon/compileapp.py", line 657, in <lambda>
    ccode = getcfs(layer, filename, lambda: compile2(code, filename))
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 205, in compile2
    return compile(code, layer, 'exec')
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/books.py", line 109
    <<<<<<< HEAD
               ^
IndentationError: expected an indented block

**Comment by bnmnetp** [comment]
Temporary glitch, sorry! fixed now.
